wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.19
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 3
      2:
      - 3
      4: 3.7.7
      5: 0.10.19
batch_size:
  desc: null
  value: 4
dataset:
  desc: null
  value: physionet2012
dropout_rate:
  desc: null
  value: 0.1
equivariance:
  desc: null
  value: true
init_lr:
  desc: null
  value: 0.0001
lr_decay_rate:
  desc: null
  value: 0.25
lr_warmup_steps:
  desc: null
  value: 2000.0
no_time:
  desc: null
  value: false
norm_type:
  desc: null
  value: reZero
num_epochs:
  desc: null
  value: 200
num_heads:
  desc: null
  value: 2
num_layers:
  desc: null
  value: 1
proj_dim:
  desc: null
  value: 8
uni_mod:
  desc: null
  value: false
